routes:
  # ----- RU страницы (пример) -----
  /ru/about/:
    data: page.about-ru          # slug страницы "about-ru"
    template: page               # используется стандартный page.hbs

  /ru/contacts/:
    data: page.contacts-ru       # slug "contacts-ru"
    template: page

  # можно добавлять сколько угодно статических RU-страниц по той же схеме
  # /ru/<url>/  -->  data: page.<slug-ru>

collections:
  /:
    permalink: /{slug}/
    filter: tag:hash-en          # slug внутреннего тега EN

  /ru/:
    permalink: /ru/{slug}/
    filter: tag:hash-ru          # slug RU


taxonomies:
  tag:    /tag/{slug}/
  author: /author/{slug}/