collections:
  /:                       
    permalink: /{slug}/
    filter: type:post+tag:-hash-guides+tag:-hash-resources
    template: index

  /guides/:
    permalink: /guides/{slug}/
    filter: tag:hash-guides+type:post
    template: guides

  /resources/:
    permalink: /resources/{slug}/
    filter: tag:hash-resources+type:post
    template: resources

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/